version: '2.0'
services:
  vocprez:
    build: 
        context: .
        dockerfile: -f Dockerfile
    image: vocprez:latest
    restart: unless-stopped
    ports:
    - "5000:5000"
    volumes:
    - $PWD/vocprez/_config/template.py:/vocprez/_config/__init__.py
   
    stdin_open: true
    tty: true