name: Run tests against Fuseki
on: push

jobs:
  db-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - name: load data into Fuseki service
        run: |
          python vocprez/_tests/_vocab_load.py

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      fuseki:
        # Docker Hub image
        image: stain/jena-fuseki
        environment:
      	  - ADMIN_PASSWORD=admin
