name: Run tests against Fuseki
on: push

jobs:
  db-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    container: python:3.7.8-slim-buster
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: load data into Fuseki service
        run: |
          pip install requests
          python vocprez/_tests/_vocabs_load.py

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      fuseki:
        # Docker Hub image
        image: stain/jena-fuseki
        env:
          ADMIN_PASSWORD: admin
